Repository mashumafi/godot-EZStorage, pull requests merged in 2022-08, with the labels that each got.

#4 Fixed a bug when reading a cache.
  addons/EZStorage/ezstorage.gd
Labels: bug

#5 Generic Storage providers
  README.md
  addons/EZStorage/directory_provider.gd
  addons/EZStorage/ezstorage.gd
  addons/EZStorage/settings.gd
  addons/EZStorage/storage_provider.gd
  screenshots/.gdignore
  screenshots/settings.png
Labels: enhancement

#6 Custom directory suffix
  README.md
  addons/EZStorage/directory_provider.gd
  addons/EZStorage/ezstorage.gd
  addons/EZStorage/storage_provider.gd
Labels: enhancement

#7 Fix issues in custom dir
  addons/EZStorage/directory_provider.gd
  addons/EZStorage/ezstorage.gd
Labels: bug

#8 Update readme and tests
  README.md
  tests/EZStorage.gd
Labels: bug, enhancement

#9 Implement file provider
  README.md
  addons/EZStorage/directory_provider.gd
  addons/EZStorage/ezcache.gd
  addons/EZStorage/ezstorage.gd
  addons/EZStorage/file_provider.gd
  addons/EZStorage/settings.gd
  addons/EZStorage/storage_provider.gd
  project.godot
  tests/EZStorage.gd
Labels: enhancement

#10 Add Directory Provider Version 2
  README.md
  addons/EZStorage/directory2_provider.gd
  addons/EZStorage/directory_provider.gd
  addons/EZStorage/ezstorage.gd
  addons/EZStorage/settings.gd
  tests/EZStorage.gd
Labels: enhancement
